using PersonalFinances.Models.Enums;

namespace PersonalFinances.Models.ViewModels;

public class FinanceViewModel
{
    public class TransactionGroup
    {
        public required string MonthYear { get; init; }
        public bool IsCurrentMonth { get; init; }
        public List<TransactionModel> Transactions { get; init; } = [];
        public decimal TotalIncome { get; init; }
        public decimal TotalExpenses { get; init; }
        public decimal Total { get; init; }
    }
    
    public List<TransactionGroup> SortedTransactionGroups { get; init; }
    public List<TransactionModel> ExpectedTransactionsThisMonth { get; init; }
    public TransactionGroup ExpectedTransactionGroupNextMonth { get; init; }

    public FinanceViewModel(List<TransactionModel> confirmedTransactions)
    {
        var today = DateOnly.FromDateTime(DateTime.Now);
        var currentMonthYear = today.ToString("MMMM yyyy");
        var daysInMonth = DateTime.DaysInMonth(today.Year, today.Month);
        var daysLeftInMonth = daysInMonth - today.Day;

        // group transactions by year and month
        SortedTransactionGroups = confirmedTransactions
            .Where(t => t.Date <= today)
            .OrderByDescending(t => t.Date)
            .GroupBy(t => t.Date.ToString("MMMM yyyy"))
            .Select(g => new TransactionGroup
            {
                MonthYear = g.Key,
                IsCurrentMonth = g.Key == currentMonthYear,
                Transactions = g.ToList(),
                TotalIncome = g.Where(t => t.IsIncome).Sum(t => t.AmountEuro),
                TotalExpenses = g.Where(t => !t.IsIncome).Sum(t => t.AmountEuro),
                Total = g.Sum(t => t.AmountEuro)
            })
            .ToList();
        
        // fill in the gaps between the first transaction and today
        var oldestGroup = SortedTransactionGroups.LastOrDefault();
        if (oldestGroup != null)
        {
            var oldestGroupDate = DateOnly.Parse(oldestGroup.MonthYear);
            var iterationGroupDate = oldestGroupDate;
            var groupCount = SortedTransactionGroups.Count;

            // fill in between the first and last transaction group
            for (var i = groupCount - 2; i >= 0; i--)
            {
                var currentGroup = SortedTransactionGroups[i];
                var expectedGroupDate = iterationGroupDate.AddMonths(1);
                var expectedMonthYear = expectedGroupDate.ToString("MMMM yyyy");
                iterationGroupDate = expectedGroupDate;

                if (currentGroup.MonthYear == expectedMonthYear) continue;

                SortedTransactionGroups.Insert(i + 1, new TransactionGroup
                {
                    MonthYear = expectedMonthYear
                });

                i++;
            }
            
            // fill in between the newest transaction group and today
            while (iterationGroupDate.Month != today.Month || iterationGroupDate.Year != today.Year)
            {
                iterationGroupDate = iterationGroupDate.AddMonths(1);
                var fillerMonthYear = iterationGroupDate.ToString("MMMM yyyy");
                
                SortedTransactionGroups.Insert(0, new TransactionGroup
                {
                    MonthYear = fillerMonthYear,
                    IsCurrentMonth = fillerMonthYear == currentMonthYear
                });
            }
        }

        ExpectedTransactionsThisMonth = [];
        ExpectedTransactionGroupNextMonth = new TransactionGroup
        {
            MonthYear = today.AddMonths(1).ToString("MMMM yyyy")
        };
        
        var nextMonth = today.AddMonths(1);
        var daysInNextMonth = DateTime.DaysInMonth(nextMonth.Year, nextMonth.Month);
        var uniqueTransactions = confirmedTransactions
            .GroupBy(t => t.Name)
            .Select(g => g.First())
            .ToList();

        // TODO: Refactor using ReoccurrenceService
        foreach (var transaction in uniqueTransactions)
        {
            var trDate = transaction.Date;
            if (transaction.Reoccurrence == Reoccurrence.Daily)
            {
                for (var i = 0; i < daysLeftInMonth; i++)
                {
                    var newTransaction = transaction.Clone(today.AddDays(i + 1));
                    // TODO: Make sure the auto-generated icon is displayed correctly
                    newTransaction.IsAutoGenerated = trDate.DayNumber < today.DayNumber;
                    ExpectedTransactionsThisMonth.Add(newTransaction);
                }

                for (var i = 0; i < daysInNextMonth; i++)
                {
                    var newDate = new DateOnly(today.Year, today.Month, 1).AddMonths(1).AddDays(i);
                    var newTransaction = transaction.Clone(newDate);
                    newTransaction.IsAutoGenerated = trDate.DayNumber < today.DayNumber;
                    ExpectedTransactionGroupNextMonth.Transactions.Add(newTransaction);
                }
            }
            else if (transaction.Reoccurrence == Reoccurrence.Weekly)
            {
                for (var i = 1; i < daysLeftInMonth; i++)
                {
                    if ((today.AddDays(i).DayNumber - trDate.DayNumber) % 7 == 0)
                    {
                        var newTransaction = transaction.Clone(today.AddDays(i));
                        newTransaction.IsAutoGenerated = trDate.DayNumber < today.DayNumber;
                        ExpectedTransactionsThisMonth.Add(newTransaction);
                    }
                }

                for (var i = 0; i < daysInNextMonth; i++)
                {
                    var newDate = new DateOnly(today.Year, today.Month, 1).AddMonths(1).AddDays(i);
                    
                    if ((newDate.DayNumber - trDate.DayNumber) % 7 != 0) continue;
                    
                    var newTransaction = transaction.Clone(newDate);
                    newTransaction.IsAutoGenerated = trDate.DayNumber < today.DayNumber;
                    ExpectedTransactionGroupNextMonth.Transactions.Add(newTransaction);
                    i += 6; // idk if this actually speeds up anything but I like to think it does
                }
            }
            else if (transaction.Reoccurrence == Reoccurrence.Monthly)
            {
                var expectedTrDay = trDate.Day > daysInNextMonth ? daysInNextMonth : trDate.Day;
                var expectedTrDate = new DateOnly(today.Year, today.Month, expectedTrDay).AddMonths(1);
                var newTransaction = transaction.Clone(expectedTrDate);
                newTransaction.IsAutoGenerated = trDate.DayNumber < today.DayNumber;
                ExpectedTransactionGroupNextMonth.Transactions.Add(newTransaction);
                
                if (trDate.Day <= today.Day) continue;
                
                var newTrDay = trDate.Day > daysInMonth ? daysInMonth : trDate.Day;
                var newTrDate = new DateOnly(today.Year, today.Month, newTrDay);
                newTransaction = transaction.Clone(newTrDate);
                newTransaction.IsAutoGenerated = trDate.DayNumber < today.DayNumber;

                ExpectedTransactionsThisMonth.Add(newTransaction);
            }
            else if (transaction.Reoccurrence == Reoccurrence.Annually)
            {
                if (trDate.Month == today.Month)
                {
                    var newTrDate = new DateOnly(today.Year, trDate.Month, trDate.Day);
                    var newTransaction = transaction.Clone(newTrDate);
                    newTransaction.IsAutoGenerated = trDate.DayNumber < today.DayNumber;
                    ExpectedTransactionsThisMonth.Add(newTransaction);
                }
                else if (trDate.Month == nextMonth.Month)
                {
                    var newTrDate = new DateOnly(today.Year, trDate.Month, trDate.Day).AddMonths(1);
                    var newTransaction = transaction.Clone(newTrDate);
                    newTransaction.IsAutoGenerated = trDate.DayNumber < today.DayNumber;
                    ExpectedTransactionGroupNextMonth.Transactions.Add(newTransaction);
                }
            }
        }
        
        ExpectedTransactionsThisMonth = ExpectedTransactionsThisMonth.OrderByDescending(t => t.Date).ToList();
    }
}