using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PersonalFinances.Models;
using PersonalFinances.Models.DataTransferObjects;
using PersonalFinances.Models.Enums;
using PersonalFinances.Models.ViewModels;
using PersonalFinances.Services;

namespace PersonalFinances.Controllers;

[Authorize]
public class FinanceController(AppDbContext dbContext, ReoccurrenceService reoccurrenceService) : Controller
{
    public async Task<IActionResult> Index()
    {
        var userName = User.FindFirstValue(ClaimTypes.NameIdentifier)!;

        // user can't be null because of the [Authorize] attribute
        var userTransactions = dbContext.Transactions
            .Include(t => t.UserModel)
            .Where(t => t.UserModel.Username == userName)
            .ToList();
        
        // Update reoccurring transactions
        var namedTransactionGroups = userTransactions
            .OrderByDescending(t => t.Date)
            .GroupBy(t => t.Name)
            .ToList();
        
        var todayDate = DateOnly.FromDateTime(DateTime.Now);

        foreach (var namedGroup in namedTransactionGroups)
        {
            var newestTransaction = namedGroup.First();
            var reoccurrence = newestTransaction.Reoccurrence;
            
            if (reoccurrence is null or Reoccurrence.None)
            {
                continue;
            }

            var trDate = newestTransaction.Date;
            var newDate = reoccurrenceService.GetNextReoccurrenceDate(trDate, (Reoccurrence)reoccurrence);
            var dayDifference = todayDate.DayNumber - newDate.DayNumber;

            while (dayDifference > 0)
            {
                var newTransactionReoc = newestTransaction.Clone(newDate);
                newTransactionReoc.IsAutoGenerated = true;
                
                dbContext.Transactions.Add(newTransactionReoc);
                userTransactions.Add(newTransactionReoc);
                
                newDate = reoccurrenceService.GetNextReoccurrenceDate(newDate, (Reoccurrence)reoccurrence);
                dayDifference = todayDate.DayNumber - newDate.DayNumber;
            }
        }

        try
        {
            await dbContext.SaveChangesAsync();
        }
        catch
        {
            ViewBag.errorMessage = "Something went wrong updating the transactions.";
        }
        
        var financeViewModel = new FinanceViewModel(userTransactions);

        return View(financeViewModel);
    }

    public IActionResult AddTransaction()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddTransaction(TransactionDto transactionData)
    {
        if (!ModelState.IsValid)
        {
            return View(transactionData);
        }

        var userName = User.FindFirstValue(ClaimTypes.NameIdentifier)!;

        // user can't be null because of the [Authorize] attribute
        var userWithTransactions = dbContext.Users
            .Include(u => u.TransactionModels)
            .FirstOrDefault(u => u.Username == userName);

        var existingTransaction = userWithTransactions!.TransactionModels
            .FirstOrDefault(t => t.Name == transactionData.Name);

        if (existingTransaction != null)
        {
            ModelState.AddModelError("Name", "Transaction with this name already exists");
            return View(transactionData);
        }

        var todayDate = DateOnly.FromDateTime(DateTime.Now);
        var date = transactionData.Date == default ? todayDate : transactionData.Date;

        var newTransaction = new TransactionModel
        {
            UserModel = userWithTransactions,
            UserModelId = userWithTransactions.Id,
            IsIncome = transactionData.IsIncome,
            AmountEuro = transactionData.AmountEuro,
            Name = transactionData.Name,
            Date = date,
            Category = transactionData.Category,
            Reoccurrence = transactionData.Reoccurrence
        };
        
        dbContext.Transactions.Add(newTransaction);
        userWithTransactions.TransactionModels.Add(newTransaction);

        try
        {
            await dbContext.SaveChangesAsync();
            return RedirectToAction("AddTransaction");
        }
        catch
        {
            ModelState.AddModelError(string.Empty, "Something went wrong saving the transaction. Please try again.");
            return View(transactionData);
        }
    }

    [HttpGet]
    public IActionResult EditTransaction(int? id)
    {
        if (id is null)
        {
            return NotFound();
        }

        var transaction = dbContext.Transactions.FirstOrDefault(t => t.Id == id);
        
        if (transaction is null)
        {
            return NotFound();
        }
        
        return View(transaction);
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    // TODO: Authorize only the user who created the transaction
    public async Task<IActionResult> EditTransaction([FromForm] TransactionModel transactionData)
    {
        if (!ModelState.IsValid)
        {
            return View("EditTransaction", transactionData);
        }
        
        var transaction = await dbContext.Transactions
            .Include(t => t.UserModel)
            .FirstOrDefaultAsync(t => t.Id == transactionData.Id);
        
        if (transaction is null)
        {
            return NotFound();
        }
        
        var userName = User.FindFirstValue(ClaimTypes.NameIdentifier)!;

        if (transaction.UserModel.Username != userName)
        {
            return Forbid();
        }

        var canUpdate = await TryUpdateModelAsync(
            transaction,
            string.Empty,
            t => t.IsIncome,
            t => t.AmountEuro,
            t => t.Name,
            t => t.Category,
            t => t.Date,
            t => t.CancelDate,
            t => t.Reoccurrence);
        
        if (!canUpdate)
        {
            ModelState.AddModelError(string.Empty, "Something went wrong updating the transaction. Please try again.");
            return View("EditTransaction", transactionData);
        }

        try
        {
            await dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        catch
        {
            ModelState.AddModelError(string.Empty, "Something went wrong updating the transaction. Please try again.");
            return View("EditTransaction", transactionData);
        }
    }

    [HttpPost]
    public async Task<IActionResult> DeleteTransaction([FromBody]int? id)
    {
        if (id == null)
        {
            return BadRequest();
        }
        
        var transaction = await dbContext.Transactions
            .Include(t => t.UserModel)
            .FirstOrDefaultAsync(t => t.Id == id);
        
        if (transaction is null)
        {
            return NotFound();
        }

        var userName = User.FindFirstValue(ClaimTypes.NameIdentifier)!;

        if (transaction.UserModel.Username != userName)
        {
            return Forbid();
        }
        
        dbContext.Transactions.Remove(transaction);

        try
        {
            await dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        catch
        {
            ModelState.AddModelError(string.Empty, "Something went wrong deleting the transaction. Please try again.");
            return View("Index");
        }
    }
}